### ISSUE TITLE
anchors in markdown

### ISSUE THREAD

**Issue by fils** [earthcubearchitecture-project418/p418Vocabulary#15]
@ashepherd  could you look over the markdown and check the anchors...

everytime I try and share a hash URL it pops around to other locations on both Firefox and Chrome...

The URL https://github.com/earthcubearchitecture-project418/p418Vocabulary#examples 

for example doesn't take me to the examples....

**Comment by ashepherd** [comment]
This works for me on Chrome(v 64)  and over at Geodex: 
http://geodex.org/voc/documentation#examples

Where does #examples deposit you? Is it consistently sending you to the 
same place, but wrong?

**Comment by fils** [comment]
@ashepherd of course now that I try it again it seems to be working...

but when I tested them for the email it seemed to always send me to the bottom regardless of the anchor I picked..   let me try and reproduce is again and screen shot it..  if I can't I'll close this issue  :)

**Comment by mike-iris** [comment]
Chrome is consistently ok when I open a new window, the Earthcube logo strip covers the first few lines,

Safari does not go to examples, but a few pages higher into the Creators/Contributors section

**Comment by ashepherd** [comment]
fixed the border overlaying the anchor.
